// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using ZeroORM.EFCore.Test.Infrastructure;

namespace ZeroORM.EFCore.Test.Infrastructure.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("ZeroORM.EFCore.Test.Infrastructure.AttributeMappedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SomeProperty")
                        .HasColumnName("StringData");

                    b.HasKey("Id");

                    b.ToTable("AttributedEntity");
                });

            modelBuilder.Entity("ZeroORM.EFCore.Test.Infrastructure.ConventionMappedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttributeMappedEntityId");

                    b.Property<string>("SomeString");

                    b.HasKey("Id");

                    b.HasIndex("AttributeMappedEntityId");

                    b.ToTable("Conventioned");
                });

            modelBuilder.Entity("ZeroORM.EFCore.Test.Infrastructure.FluentMappedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConventionMappedEntityId");

                    b.Property<string>("SomeProperty")
                        .HasColumnName("ReallyUnexpectedColumnName");

                    b.HasKey("Id");

                    b.HasIndex("ConventionMappedEntityId");

                    b.ToTable("SomeReallyUnrelatedName");
                });

            modelBuilder.Entity("ZeroORM.EFCore.Test.Infrastructure.ConventionMappedEntity", b =>
                {
                    b.HasOne("ZeroORM.EFCore.Test.Infrastructure.AttributeMappedEntity", "AttributeMappedEntity")
                        .WithMany()
                        .HasForeignKey("AttributeMappedEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZeroORM.EFCore.Test.Infrastructure.FluentMappedEntity", b =>
                {
                    b.HasOne("ZeroORM.EFCore.Test.Infrastructure.ConventionMappedEntity", "ConventionMappedEntity")
                        .WithMany()
                        .HasForeignKey("ConventionMappedEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
